# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -Dmaven.test.skip=true'
- script: 'mv target/JMSReceiver-*.war target/JMSReceiver.war'
- script: 'ls -ltr target/'
- script: docker build -t 'mssdockerregistry.azurecr.io/jmsreceiver' .
- script: docker login -u 'mssdockerregistry' -p "2YcriYYzQ+Qfrrf/8mXQVYVcTqC41eUr" mssdockerregistry.azurecr.io
- script: docker push 'mssdockerregistry.azurecr.io/jmsreceiver'